openapi: 3.0.2
info:
  title: OPENAPI-SAMPLE-STRUCTURE-PERSON-DETAILS
  description: Example OpenAPI document for Person Details
  contact:
    name: WebFlux Sample
    email: webflux.sample@email.com
  version: 1.0.0
servers:
  - url: https://api-dev.webflux.sample/enroll/v1
    description: DEVELOPMENT
  - url: https://api-qa.webflux.sample/enroll/v1
    description: QA
  - url: https://api-homolog.webflux.sample/enroll/v1
    description: HOMOLOG
  - url: https://api.webflux.sample/enroll/v1
    description: PRODUCTION

tags:
  - name: Address
  - name: Phone

paths:
  /address:
    post:
      tags:
        - Address
      summary: Create a new address for one person
      security:
        - BearerAuth: []
        - OauthSecurityUser:
            - write
            - read
      description: |
        
        ## Responsibilities
        This endpoint has the function of registering a new **address** for the user.
        Create address.

        ---
        ## Requirements
        To access this endpoint, you must have one of the following sets of roles:
        * `AUTH-BASIC` roles

      operationId: createAddress
      requestBody:
        required: true
        description: "Address information"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddressRequestBody"
      responses:
        201:
          $ref: "#/components/responses/AddressCreatedResponse"
    get:
      tags:
        - Address
      summary: Find address
      security:
        - BearerAuth: []
        - OauthSecurityUser:
            - write
            - read
      description: |
        
        ## Responsibilities
        This endpoint has the function of finding address.

        ---
        ## Requirements
        To access this endpoint, you must have one of the following sets of roles:
        * `AUTH-BASIC` role

      operationId: findAddress
      parameters:
        - in: query
          name: street
          example: "Street name"
          schema:
            type: string
        - in: query
          name: zipcode
          example: "12090001"
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/AddressReadResponse'
  /phone:
    post:
      tags:
        - Phone
      summary: Create a new phone to the person
      security:
        - BearerAuth: []
        - OauthSecurityUser:
            - write
            - read
      description: |
        
        ## Responsibilities
        Create phone

        ---
        ## Requirements
        To access this endpoint, you must have one of the following sets of roles:
        * `AUTH-BASIC` role

      operationId: createPhone
      requestBody:
        required: true
        description: "Phone information"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PhoneRequestBody"
      responses:
        201:
          $ref: "#/components/responses/PhoneCreatedResponse"
    get:
      tags:
        - Phone
      summary: Find Phone
      security:
        - BearerAuth: []
        - OauthSecurityUser:
            - write
            - read
      description: |
        
        ## Responsibilities
        This endpoint has the function of finding phones.

        ---
        ## Requirements
        To access this endpoint, you must have one of the following sets of roles:
        * `AUTH-BASIC` role

      operationId: findPhone
      parameters:
        - in: query
          name: phone
          example: "+55121234567890"
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/PhoneReadResponse'

components:
  securitySchemes:
    OauthSecurityUser:
      type: oauth2
      flows:
        password:
          tokenUrl: https://api-dev.webflux.sample/security/v1/oauth2/login
          scopes:
            read: User read scope
            write: User write scope
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
#  parameters:
#    QueryLimit:
#      name: limit
#      in: query
#      schema:
#        type: integer
#        default: 20
#      description: Total count of registries to fetch.
#    QueryOffset:
#      name: offset
#      in: query
#      schema:
#        type: integer
#        default: 0
#      description: From which index to seek for registries.
#    QuerySort:
#      name: sort
#      in: query
#      schema:
#        type: string
#        example: name
#        default: id
#      description: Named field to sort results by
  schemas:
    AddressRequestBody:
      required:
        - personId
        - street
        - number
        - zipcode
        - city
      type: object
      properties:
        personId:
          type: string
          minLength: 1
          example: "67fe5f70f5c8e0274f05aee4"
        street:
          type: string
          minLength: 1
          maxLength: 200
          example: "Street name test"
        number:
          type: integer
          example: 1234
        zipcode:
          type: string
          minLength: 1
          maxLength: 15
          example: "12090000"
        city:
          type: string
          minLength: 1
          example: "New York"
    AddressCreatedResponseBody:
      type: object
      properties:
        id:
          type: string
          example: 620eb80e0f9f7c26ba190dfc
    AddressReadResponseBody:
      type: object
      properties:
        personId:
          type: string
          example: 620eb80e0f9f7c26ba190dfc
        street:
          type: string
          example: Street name sample
        number:
          type: integer
          example: 1234
        zipcode:
          type: string
          example: 12090000
        city:
          type: string
          example: New York
        active:
          type: boolean
          example: true
        createdAt:
          type: string
          example: "2025-04-20T21:18:23.524+00:00"
        updatedAt:
          type: string
          example: "2025-04-20T21:18:23.524+00:00"
        deletedAt:
          type: string
          example: "2025-04-20T21:18:23.524+00:00"
    PhoneRequestBody:
      required:
        - personId
        - phoneNumber
        - phoneType
      type: object
      properties:
        personId:
          type: string
          minLength: 1
          example: "67fe5f70f5c8e0274f05aee4"
        phoneNumber:
          type: string
          minLength: 1
          maxLength: 15
          example: "+55121234567890"
        phoneType:
          type: string
          example: "mobile"
          enum: ["mobile", "home", "office"]
    PhoneCreatedResponseBody:
      type: object
      properties:
        id:
          type: string
          example: 620eb80e0f9f7c26ba190dfc
    PhoneReadResponseBody:
      type: object
      properties:
        personId:
          type: string
          example: 620eb80e0f9f7c26ba190dfc
        phoneNumber:
          type: string
          example: "+5512990990900"
        phoneTYpe:
          type: string
          example: "mobile"
        active:
          type: boolean
          example: true
        createdAt:
          type: string
          example: "2025-04-20T21:18:23.524+00:00"
        updatedAt:
          type: string
          example: "2025-04-20T21:18:23.524+00:00"
        deletedAt:
          type: string
          example: "2025-04-20T21:18:23.524+00:00"
  responses:
    AddressCreatedResponse:
      description: Address Created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AddressCreatedResponseBody'
    AddressReadResponse:
      description: Address List
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AddressReadResponseBody'
    PhoneCreatedResponse:
      description: Phone Created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PhoneCreatedResponseBody'
    PhoneReadResponse:
      description: Phone List
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PhoneReadResponseBody'